### ISSUE TITLE
COMPLETE - SEO - add meta description

### ISSUE THREAD

**Issue by gacetta** [roundhousedesigns/rise-frontend#58]
Lighthouse Report: Document does not have a meta description.  Meta descriptions may be included in search results to concisely summarize page content. [Learn more about the meta description](https://developer.chrome.com/docs/lighthouse/seo/meta-description/?utm_source=lighthouse&utm_medium=devtools).

@gaswirth - do you have a clear, concise paragraph description for RISE that can be used as "content" for meta tag

**Comment by gaswirth** [comment]
@gacetta Yar! 

> RISE Theatre Directory is a national personnel directory created to promote visibility of individuals who work backstage, behind-the-scenes, and in support of theater making. The directory is a public service tool, available to all, created with the knowledge that amplification is particularly powerful for those who are often overlooked, including but not limited to people of color, women, trans, nonbinary, deaf, and disabled theatre professionals. RISE Theatre Directory allows these professionals to be discovered and identified for employment and opportunities by producers, general managers, theaters and various employers. Membership is free for professionals across more than 120+ job categories, including Choreography, Costume Design, Direction, Hair/Make-up, Lighting, Management, Music, Producing, Props, Scenic/Carpentry, Sound, and Writing, among others.

**Comment by gacetta** [comment]
Thanks @gaswirth!  
- Created a meta description element in index.html using the above content.
- Re-ran lighthouse tests (on landing page after login) and got a score of 100.  
<img width="763" alt="Screen Shot 2023-06-23 at 2 24 08 PM" src="https://github.com/roundhousedesigns/rise-frontend/assets/78240758/c2543254-4798-4cbb-ab07-35fab6159253">
