### ISSUE TITLE
Skills List - Can we add "Timpani" ?

### ISSUE THREAD

**Issue by cheesehero112** [roundhousedesigns/rise-frontend#61]
@gaswirth This is more of a request/ suggestion - in the search > "what skills are you looking for?" section, there are many different percussion instruments listed, but timpani is not included. Considering how doubles are handled, it's great to include timpani in the list. (If a show had marimba, latin percussion, and timpani, that counts as 3 doubles)

![Screenshot 2023-06-23 at 1 41 38 PM](https://github.com/roundhousedesigns/rise-frontend/assets/102322200/e77eb00b-5259-4f17-958c-2c183f2b7aca)

**Comment by gaswirth** [comment]
I will pass this along to the team! Thanks.

**Comment by gaswirth** [comment]
@cheesehero112 We're adding Timpani!! 🚀

**Comment by cheesehero112** [comment]
YAY! Thank you! 🥁
