### ISSUE TITLE
Search by Name function does not work

### ISSUE THREAD

**Issue by cheesehero112** [roundhousedesigns/rise-frontend#62]
To test, I typed "Chihiro", "Chihiro Shibayama", "chihiro" and clicked on the search icon but nothing happens.
I know my profile exist and shows up when I search using filters, so something is not working in the search by name.

**Comment by gaswirth** [comment]
Strange! When I search "Chihiro," I actually get 2 results! Are you clicking the search icon next to the search-by-name field. When you search other names, do they appear?

**Comment by cheesehero112** [comment]
@gaswirth Yeah, I suspected that I may have two profiles (one is from when it was still GTW, and another one I made once it was RISE). I should delete the other one but lost the password...

Strange enough, now I tried again, it's working fine - it took me to search result page.

**Comment by gaswirth** [comment]
Hmm. Odd. Let me know if it happens again. As for the 2 accounts, no worries -- just a dev server with old, stale, and usually fake data 😜

**Comment by cheesehero112** [comment]
Will do! Glad it wasn't a real bug.
