### ISSUE TITLE
List of "skills" in Edit Credit modal are truncated when too many items are returned

### ISSUE THREAD

**Issue by gaswirth** [roundhousedesigns/rise-frontend#65]
When editing a Credit (and possibly elsewhere), if you select enough jobs that too many related Skills are populating the list, the query results get cut off and/or are truncated in strange ways.  Best initial guess: GraphQL maxing out at 100 requests (which we have no control over). Need to figure out how to do multiple requests, or chained requests, etc, to populate full list.

**Comment by gaswirth** [comment]
The best job to use this for is **Music**-->**Pit Musician (Other)**, as it brings up a very large list of instruments. Easy to hit the max with this one.

**Comment by ari-denary** [comment]
@gaswirth - I've been exploring the codebase & testing the site to recreate this error. When editing a credit, I am able to view all skills, but have found that there is a max of 10 skills retained per credit.  Upon saving, initially all selected skills show under the credit, but once I refresh, only the first 10 alphabetic skills remain. 

I just wanted to confirm my understanding to see if this is the same truncating issue you experienced, or if I should log this as a separate issue?

**Comment by gaswirth** [comment]
@ari-denary Thanks for this! This actually isn't the issue I mentioned, but I'm grateful for your uncovering it! Would you mind creating a new issue for us to track this? I'll take a look in the next couple of days -- would be curious to hear if you were able to sniff out the cause on the frontend. I have a hunch this is a backend issue, but looking forward to seeing the new ticket.

Thanks!

**Comment by ari-denary** [comment]
Absolutely! Issue #73 created.  I'll also dive deeper tomorrow and see if I can root out the cause.

**Comment by gaswirth** [comment]
Stale! Please reopen if necessary.
