### ISSUE TITLE
Re-rendering loop at breakpoints

### ISSUE THREAD

**Issue by gacetta** [roundhousedesigns/rise-frontend#78]
This occurs on an individual profile page (only those with a photo I think?):

When resizing browser window to an extreme portrait mode (horizontally narrow, vertically tall), the page flashes / refreshes indefinitely.  When re-rendering, no photo is shown, just the colorful circle with initials.
To recreate - load profile page in a typical landscape ratio.  Then drag sidebar to make screen narrower until the proper breakpoint ratio is hit.

Thoughts: it's related to the profile image sizing

**Comment by gaswirth** [comment]
Fixed as part of minor UI enhancements in 1.0.8.
