### ISSUE TITLE
COMPLETE (@Gacetta) - Improve: Add drag-and-drop to images

### ISSUE THREAD

**Issue by gaswirth** [roundhousedesigns/rise-frontend#84]
Image uploaders should have drag-and-drop capability. Let's add it!

**Comment by gacetta** [comment]
@gaswirth I'm going to look into this one.

do you have any description / examples of how you'd like it to look, or should I come up with something I like and "audition" it for you?

**Comment by gacetta** [comment]
Made some good progress implementing the component to trigger on both drag and drop and on click.  

At the moment there is no actual uploading functionality, just a console.log to check.

**Comment by gaswirth** [comment]
Closed with PR #90
