### ISSUE TITLE
uploaded resume preview

### ISSUE THREAD

**Issue by gacetta** [roundhousedesigns/rise-frontend#93]
As discussed with @gaswirth, when editing a profile, it would be more clear for the user to render a small image preview of the uploaded resume (in place of the "preview resume" button?)

EXTRA CREDIT: onClick of the resume preview, a dialog pops open and the resume fills the screen.

**Comment by gaswirth** [comment]
Checking in on some old items! Any change that @gacetta wants to take a stab? 🤞🏻 😜

**Comment by gacetta** [comment]
It has been a while.  I'll take a stab at this one
